project:
  type: website
  output-dir: docs

website:
  title: "Savvyuni MT"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv-academic-Rohan_Alexander.pdf
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



